apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-api.fullname" . }}-config
  namespace: {{ .Values.namespace | default "todo-app" }}
  labels:
    {{- include "todo-api.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  PORT: {{ .Values.app.port | quote }}