{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "todo-api.fullname" . }}
  namespace: {{ .Release.Namespace }}

  labels:
    release: monitoring
    {{- include "todo-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "todo-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{- end }}
