apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: todo-app
  labels:
    app: todo-api
spec:
  type: NodePort                   
  selector:
    app: todo-api                  
  ports:
  - name: http
    protocol: TCP
    port: 80                       
    targetPort: 3000               
    nodePort: 30080                
  sessionAffinity: None